name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#both')
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: maizecyber
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: maizecyber/ankibot:gcpv1.1

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#both')
    needs: docker
    environment: production
    env:
      TF_VAR_discord_bot_token: ${{ secrets.DISCORD_TOKEN }}
      TF_VAR_secret_trigger: ${{ github.run_id }}
      TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
      TF_VAR_project_region: ${{ secrets.PROJECT_REGION }}
      TF_VAR_project_zone: ${{ secrets.PROJECT_ZONE }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v3'
      with:
        project_id: ${{ secrets.PROJECT_NAME }}
        workload_identity_provider: 'projects/334515927364/locations/global/workloadIdentityPools/gh-action-minecraft-pool/providers/github-provider'
        service_account: 'github-deployer@${{ secrets.PROJECT_NAME }}.iam.gserviceaccount.com'

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
    #  run: terraform fmt -check

    # Runs a validation check on terraform code
    - name: Terraform Validate
      run: terraform validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    # This job only runs if the commit message contains "#deploy"
    - name: Terraform Apply

      run: terraform apply -auto-approve -input=false

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    #- name: Terraform Apply
    #  if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
    #  run: terraform apply -auto-approve -input=false
